// Data models — auto-generated by /vibe-data-prep
// Run the data prep prompt to populate this file with typed models
// matching your customer's CSV column headers.

namespace Api.Models;

/// <summary>
/// Example record type. Replace with generated models after data prep.
/// </summary>
public record SampleRecord(
    string Id,
    string Name,
    string Category,
    double Value,
    string Date
);
