<#
.SYNOPSIS
    Generate TypeScript interfaces and C# record types from CSV headers.
.DESCRIPTION
    Reads CSV column headers and infers types to generate strongly-typed
    models for both the React frontend and .NET API backend.
.EXAMPLE
    pwsh scaffold/data/scripts/generate-models.ps1
#>

param(
    [string]$DataPath = (Join-Path $PSScriptRoot ".."),
    [string]$TsOutput = (Join-Path $PSScriptRoot "../../web/src/types/data.ts"),
    [string]$CsOutput = (Join-Path $PSScriptRoot "../../api/Models/DataModels.cs")
)

$csvFiles = Get-ChildItem -Path $DataPath -Filter "*.csv" -File |
    Where-Object { $_.DirectoryName -eq (Resolve-Path $DataPath).Path }

if ($csvFiles.Count -eq 0) {
    Write-Host "No CSV files found in $DataPath" -ForegroundColor Yellow
    exit 0
}

$tsLines = @("// Auto-generated by generate-models.ps1 — do not edit manually", "")
$csLines = @(
    "// Auto-generated by generate-models.ps1 — do not edit manually",
    "",
    "namespace Api.Models;",
    ""
)

foreach ($file in $csvFiles) {
    $data = Import-Csv -Path $file.FullName
    $baseName = [System.IO.Path]::GetFileNameWithoutExtension($file.Name) -replace '[^a-zA-Z0-9]', ''
    $pascalName = ($baseName.Substring(0, 1).ToUpper() + $baseName.Substring(1))

    $headers = $data[0].PSObject.Properties.Name

    # TypeScript interface
    $tsLines += "export interface $pascalName {"
    foreach ($h in $headers) {
        $clean = ($h -replace '\s+', '_' -replace '[^a-zA-Z0-9_]', '').ToLower()
        $tsLines += "  $clean: string;"
    }
    $tsLines += "}"
    $tsLines += ""

    # C# record
    $csParams = $headers | ForEach-Object {
        $clean = ($_ -replace '\s+', '' -replace '[^a-zA-Z0-9]', '')
        "    string $clean"
    }
    $csLines += "public record $pascalName("
    $csLines += ($csParams -join ",`n")
    $csLines += ");"
    $csLines += ""

    Write-Host "Generated models for: $($file.Name) -> $pascalName" -ForegroundColor Green
}

# Ensure output directories exist
$tsDir = Split-Path $TsOutput -Parent
$csDir = Split-Path $CsOutput -Parent
if (-not (Test-Path $tsDir)) { New-Item -ItemType Directory -Path $tsDir -Force | Out-Null }
if (-not (Test-Path $csDir)) { New-Item -ItemType Directory -Path $csDir -Force | Out-Null }

$tsLines | Out-File -FilePath $TsOutput -Encoding utf8
$csLines | Out-File -FilePath $CsOutput -Encoding utf8

Write-Host "`nGenerated:" -ForegroundColor Cyan
Write-Host "  TypeScript: $TsOutput" -ForegroundColor Gray
Write-Host "  C#: $CsOutput" -ForegroundColor Gray
