// Shared gate-computation logic for the VIBE engine.
//
// Single source of truth for how an engagement's gate state is derived from its
// artifacts. Used by scripts/gen-gates.mjs (writes the committed gates.json) and
// by the web surface server (renders gate tiles + grade badges live). Keeping it
// in one place means the CLI and the UI can never disagree.

import { readFileSync, existsSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { execSync } from 'node:child_process';
import { createHash } from 'node:crypto';

export const GATES = {
  discover: {
    files: ['personas.md', 'problem-statement.md', 'current-state-journey.md'],
    requireSignoff: [],
  },
  disrupt: {
    files: ['selected-concept.md', 'future-state-journey.md', 'storyboard.md'],
    requireSignoff: ['selected-concept.md'],
  },
};
const RANK = { A: 3, B: 2, C: 1 };

export function blobSha(path) {
  try { return execSync(`git hash-object "${path}"`, { encoding: 'utf8' }).trim(); }
  catch { return null; }
}

// Pure-JS equivalent of `git hash-object` for in-memory content (no working tree).
// Lets the web surface compute the same SHA the engine commits, so a server-side
// gate refresh binds sign-off to the exact bytes git will store.
export function gitBlobSha(content) {
  const buf = Buffer.from(content, 'utf8');
  return createHash('sha1').update(`blob ${buf.length}\0`).update(buf).digest('hex');
}

export function lowestGrade(text) {
  // Grade-marker styles seen across the deliverables. The engine isn't perfectly
  // deterministic about phrasing, so all three are matched robustly:
  //   Form A  `> **Grade:** A`         (colon form — personas template pins this)
  //   Form B  `**Grade A** — …`        (inline bold form)
  //   Form C  `> **Current grade: A**` (bold span ending in the grade letter — what
  //                                      the engine improvises when a template does
  //                                      NOT pin Form A; e.g. problem-statement,
  //                                      current-state-journey before the marker fix)
  // Rubric prose like `**Grade A (Strong)**` or `**Grade B or higher**` is excluded
  // from every form: it has no colon (fails A), the letter is followed by " (" / " or"
  // not "**" (fails B), and the letter is not adjacent to the closing `**` (fails C).
  const found = [];
  for (const m of text.matchAll(/\*\*Grade:\*{0,2}\s*([ABC])\b/gi)) found.push(m[1].toUpperCase());
  for (const m of text.matchAll(/\*\*Grade\s+([ABC])\*\*/gi)) found.push(m[1].toUpperCase());
  for (const m of text.matchAll(/\*\*[^*]*\bgrade\s*[:\-–—]?\s*([ABC])\*\*/gi)) found.push(m[1].toUpperCase());
  if (!found.length) return null;
  return found.reduce((lo, g) => (RANK[g] < RANK[lo] ? g : lo), found[0]);
}

export function signoff(text) {
  const sec = text.split(/##\s*Sign-?off/i)[1];
  if (!sec) return null;
  for (const line of sec.split(/\r?\n/)) {
    const m = line.match(/^\|\s*([^|]+?)\s*\|\s*([^|]+?)\s*\|\s*([^|]+?)\s*\|/);
    if (!m) continue;
    const name = m[1].trim();
    if (!name || /\{\{/.test(name) || /^reviewed by$/i.test(name) || /^-+$/.test(name)) continue;
    return { by: name, role: m[2].trim(), at: m[3].trim() };
  }
  return null;
}

// ---- Provenance ("receipts") ----------------------------------------------
// The deliverable prompts MANDATE source attribution (every quote must cite a
// `sources/` file; "no source citation" is a Grade-C failure). The engine therefore
// already emits citations inline, in a few stable shapes:
//   • file-level header  `> **Sources read:** \`sources/x.md\`, \`sources/y.md\``
//   • personas quote     `> — Priya, source: \`sources/x.md\` line 46`
//   • inferred block     `> _No direct quote — … inferred from \`sources/x.md\`._`
//   • table-cell ref     `| **But** | … | \`sources/x.md\` | line 30 |`
// extractProvenance reads those without re-grading anything: it surfaces what the
// graded engine already wrote. It MUST NEVER throw — provenance is additive; a parse
// miss degrades to "fewer receipts shown", never a broken board.
const PROV_EXT = 'md|txt|vtt|srt|csv|tsv|json|docx|pptx|xlsx|xls|pdf';
const PROV_PATH = new RegExp('`((?:sources|engagement)/[^`]+?\\.(?:' + PROV_EXT + '))`', 'gi');
// Metadata lines carry source paths but aren't per-claim citations — they feed the
// file-level sources[] list, not the citation count.
const PROV_META = /\*\*Sources read|Auto-generated by|Discover deliverable|Disrupt deliverable/i;

function provResolve(raw, known) {
  if (!known.length || known.includes(raw)) return raw;
  const base = raw.split('/').pop().toLowerCase();
  return known.find((p) => p.split('/').pop().toLowerCase() === base) || raw;
}

function provClip(s) {
  const t = s.replace(/^\s*[>|]+\s*/, '').replace(/\s+/g, ' ').trim();
  return t.length > 240 ? t.slice(0, 237) + '…' : t;
}

// Returns { sources[], citations[], supportMix } for one deliverable.
//   sources   – every source/engagement file the deliverable references (deduped,
//               basename-resolved against knownSourcePaths when supplied)
//   citations – per-claim receipts, each tagged with a support tier:
//                 'quoted'   🟢 direct evidence (a path on a claim/quote line)
//                 'reasoned' 🔵 explicit inference ("inferred from", "no direct quote")
//               ('design-choice' ⚪ — an unsourced claim — is a rendering concept the
//                ledger derives from un-tagged lines; it isn't parsed here.)
//   supportMix – counts of the tiers above
export function extractProvenance(text, knownSourcePaths = []) {
  const empty = { sources: [], citations: [], supportMix: { quoted: 0, reasoned: 0 } };
  if (typeof text !== 'string' || !text) return empty;
  try {
    const known = Array.isArray(knownSourcePaths) ? knownSourcePaths : [];
    const sources = [];
    const seen = new Set();
    for (const m of text.matchAll(PROV_PATH)) {
      const p = provResolve(m[1], known);
      if (!seen.has(p)) { seen.add(p); sources.push(p); }
    }

    const citations = [];
    let pendingQuote = null; // a `> "…"` line whose attribution lands a line or two later
    for (const line of text.split(/\r?\n/)) {
      const paths = [...line.matchAll(PROV_PATH)].map((m) => provResolve(m[1], known));
      const quoteM = line.match(/"([^"]{6,})"/);
      if (quoteM && /^\s*>/.test(line) && !/source\s*:/i.test(line) && !paths.length) {
        pendingQuote = quoteM[1];
      }
      if (!paths.length || PROV_META.test(line)) continue;
      const uniq = [...new Set(paths)];
      if (/inferred|no direct quote/i.test(line)) {
        for (const p of uniq) citations.push({ source: p, support: 'reasoned', raw: provClip(line) });
        pendingQuote = null;
        continue;
      }
      const speakerM = line.match(/—\s*([^,|]+?),\s*source\s*:/i);
      const quote = quoteM ? quoteM[1] : (/source\s*:/i.test(line) ? pendingQuote : null);
      citations.push({
        source: uniq[0], support: 'quoted',
        quote: quote || null, speaker: speakerM ? speakerM[1].trim() : null, raw: provClip(line),
      });
      for (const extra of uniq.slice(1))
        citations.push({ source: extra, support: 'quoted', quote: null, speaker: null, raw: provClip(line) });
      pendingQuote = null;
    }

    const supportMix = { quoted: 0, reasoned: 0 };
    for (const c of citations) supportMix[c.support]++;
    return { sources, citations, supportMix };
  } catch { return empty; }
}

// Best-effort enumeration of an engagement's known source files (for basename
// resolution): everything under the repo's sources/ tree plus the engagement's own
// folder (briefs, PROJECT-CONTEXT). Never throws.
function listKnownSources(dir) {
  const known = [];
  const walk = (abs, rel) => {
    let ents;
    try { ents = readdirSync(abs, { withFileTypes: true }); } catch { return; }
    for (const e of ents) {
      const a = join(abs, e.name);
      const r = rel ? `${rel}/${e.name}` : e.name;
      if (e.isDirectory()) walk(a, r);
      else known.push(r);
    }
  };
  walk(join(dir, '..', '..', 'sources'), 'sources');
  const name = dir.split(/[\\/]/).filter(Boolean).pop();
  walk(dir, `engagement/${name}`);
  return known;
}

// Evaluate a single present artifact. `prior` is that artifact's record from an
// earlier gates.json (or undefined): if it was signed by the same person, its
// sign-off SHA carries forward so an edit-after-sign-off flips it stale.
function evalArtifact(text, sha, prior, knownSourcePaths = []) {
  const grade = lowestGrade(text);
  const so = signoff(text);
  const wasSigned = prior?.signedOffSha;
  const signedOffSha = so
    ? (wasSigned && prior.signedOffBy === so.by ? wasSigned : sha)
    : null;
  const isStale = !!(so && signedOffSha && signedOffSha !== sha);
  const prov = extractProvenance(text, knownSourcePaths);
  return {
    present: true,
    grade,
    gradePass: grade ? RANK[grade] >= RANK.B : false,
    signedOffBy: so?.by ?? null,
    signedOffAt: so?.at ?? null,
    sha,
    signedOffSha,
    stale: isStale,
    sources: prov.sources,
    citations: prov.citations,
    supportMix: prov.supportMix,
  };
}

// Build the top-level reverse index: for each source file, which deliverables cite
// it and how many citations in total. Powers the bucket's "Used by" chips.
function rollupProvenance(out) {
  const bySource = {};
  for (const [file, a] of Object.entries(out.artifacts)) {
    if (!a || !a.present) continue;
    const used = new Set([...(a.sources || []), ...((a.citations || []).map((c) => c.source))]);
    for (const s of used) {
      (bySource[s] ||= { usedBy: [], citationCount: 0 });
      if (!bySource[s].usedBy.includes(file)) bySource[s].usedBy.push(file);
    }
    for (const c of a.citations || []) {
      (bySource[c.source] ||= { usedBy: [], citationCount: 0 });
      bySource[c.source].citationCount++;
    }
  }
  out.provenance = { bySource };
}

// Roll the per-artifact records up into gate statuses + handoffReady, in place.
function rollup(out) {
  for (const [gate, cfg] of Object.entries(GATES)) {
    let present = 0, passing = 0, signedOk = true, stale = false;
    for (const f of cfg.files) {
      const a = out.artifacts[f];
      if (!a || !a.present) continue;
      present++;
      if (a.gradePass) passing++;
      if (cfg.requireSignoff.includes(f) && !a.signedOffBy) signedOk = false;
      if (a.stale) stale = true;
    }
    const complete = present === cfg.files.length;
    out.gates[gate] = {
      status: complete && passing === cfg.files.length && signedOk && !stale ? 'GREEN'
        : present === 0 ? 'NOT_STARTED' : 'INCOMPLETE',
      artifactsPresent: `${present}/${cfg.files.length}`,
      gradePassing: `${passing}/${cfg.files.length}`,
      signoffOk: signedOk,
      stale,
    };
  }
  out.handoffReady = out.gates.discover.status === 'GREEN' && out.gates.disrupt.status === 'GREEN';
  rollupProvenance(out);
}

// Compute the full gate object for an engagement directory. `prior` is an earlier
// gates.json (or {}), used to carry sign-off SHAs forward so edit-after-sign-off
// flips an artifact stale.
export function computeGates(dir, prior = { artifacts: {} }) {
  const out = {
    engagement: dir.split(/[\\/]/).filter(Boolean).pop(),
    generatedAt: new Date().toISOString(),
    artifacts: {},
    gates: {},
  };

  const known = listKnownSources(dir);
  for (const cfg of Object.values(GATES)) {
    for (const f of cfg.files) {
      const p = join(dir, f);
      if (!existsSync(p)) { out.artifacts[f] = { present: false }; continue; }
      out.artifacts[f] = evalArtifact(readFileSync(p, 'utf8'), blobSha(p), prior.artifacts?.[f], known);
    }
  }

  rollup(out);
  try { out.commitSha = execSync('git rev-parse HEAD', { cwd: dir, encoding: 'utf8' }).trim(); }
  catch { out.commitSha = null; }
  return out;
}

// Same computation as computeGates, but driven by in-memory file contents instead
// of a working tree. `contents` maps each gate filename to its text (or null when
// absent). Lets the web surface refresh gates.json from the GitHub Contents API
// after a web sign-off — sharing evalArtifact/rollup means it can never disagree
// with the CLI generator.
export function computeGatesFromContents(engagement, contents, prior = { artifacts: {} }, commitSha = null, knownSourcePaths = []) {
  const out = { engagement, generatedAt: new Date().toISOString(), artifacts: {}, gates: {} };
  for (const cfg of Object.values(GATES)) {
    for (const f of cfg.files) {
      const text = contents[f];
      if (text == null) { out.artifacts[f] = { present: false }; continue; }
      out.artifacts[f] = evalArtifact(text, gitBlobSha(text), prior.artifacts?.[f], knownSourcePaths);
    }
  }
  rollup(out);
  out.commitSha = commitSha;
  return out;
}
